### PR TITLE
Update IceChecklistEntry.cs

### PR DESCRIPTION
**Pull request by alextatham**
Modified Priority to use 4 byte uint instead of 8byte ulong.

### CODE REVIEW

**Comment by alextatham** [comment]
This is an additional change following the ulong to uint changes you made last night.

I have tested this change and this resolves the issues I was having.

**Comment by sipsorcery** [comment]
Thx for the PR. You're right I did miss a step. The correct fix is to leave the `Priority` as `ulong` and to use the new `LocalPriority` field in the STUN PRIORITY attribute instead. That change is on line 1261 of `RtpIceChannel.cs`.

**Review by sipsorcery — CHANGES_REQUESTED** [review]
Leave this as ulong and instead use the uint LocalPriority field for the STUN PRIORITY attribute.

**Comment by sipsorcery** [comment]
I've applied the fix for this PR in fc734df2. If you'd like the contributor credit I can adjust the commit message but need to know your email address (can be the private GitHub one).

**Pull request closed without merging**
